(require "player_207823589_CarrascoAlvarez.rkt")
(require "board_207823589_CarrascoAlvarez.rkt")
(require "utils_207823589_CarrascoAlvarez.rkt")
(require "game_207823589_CarrascoAlvarez.rkt")

;# TDA player (RF2)
(define p1 (player 1 "YOLO" "red" 0 0 0 1))
(displayln p1)
(define p2 (player 2 "MatesMike" "yellow" 0 0 0 314))
(displayln p2)
(define p3 (player 3 "Chimango" "green" 1 2 3 23))
(displayln p3)

;# TDA piece (RF3)
(define pz1 (piece "red"))
(define pz2 (piece "yellow"))
(define pz3 (piece "green"))

;# TDA Board (RF4)
(define b0 (board))
(display-board b0)
;(RF5, RF6)
(define b1 (board-set-play-piece b0 0 pz1))
(display-board b1)
(define b2 (board-set-play-piece b1 0 pz1))
(display-board b2)
(define b3 (board-set-play-piece b2 0 pz1))
(display-board b3)
(define b4 (board-set-play-piece b3 1 pz2))
(display "\nboard-can-play? b0: ")
(display (board-can-play? b0))
(display "\nboard-can-play? b3: ")
(display (board-can-play? b3))
(display "\nboard-can-play? b0: ")
(display (board-can-play? b4))

;(RF7,RF8,RF9)
(board-check-vertical-win b1)
(board-check-vertical-win b3)
(define b4b (board-set-play-piece b4 0 pz1))
(display-board b4b)
(display "Win vertical en tablero b4b?:\n")
(display (board-check-vertical-win b4b))

(board-check-horizontal-win b3)
(board-check-horizontal-win b4)
(define b5 (board-set-play-piece b4 2 pz2))
(define b6 (board-set-play-piece b5 3 pz2))
(define b6b (board-set-play-piece b6 4 pz2))
(display-board b6b)
(display "Win horizontal en tablero b6b?: ")
(display (board-check-horizontal-win b6b))

(board-check-diagonal-win b1)
(board-check-diagonal-win b3)
(define b7 (board-set-play-piece b6 1 pz1))
(define b8 (board-set-play-piece b7 2 pz2))
(define b9 (board-set-play-piece b8 2 pz1))
(define b10 (board-set-play-piece b9 3 pz2))
(define b11 (board-set-play-piece b10 3 pz2))
(define b12 (board-set-play-piece b11 3 pz1))
(define b13 (board-set-play-piece b12 4 pz2))
(define b14 (board-set-play-piece b13 4 pz2))
(define b15 (board-set-play-piece b14 4 pz2))
(define b16 (board-set-play-piece b15 4 pz1))
(display-board b15)
(display "Win diagonal en tablero b15?: ")
(display (board-check-diagonal-win b15))

(display-board b16)
(display "Win diagonal en tablero b16?: ")
(display (board-check-diagonal-win b16))

; (RF10)
(display-board empty-board)
(display "\nGanador de tablero vacío?: ")
(display (board-who-is-winner? empty-board))

(display-board b4b)
(display "\nGanador de tablero b4b?: ")
(board-who-is-winner? b4b)

(display-board b6b)
(display "\nGanador de tablero b6b?: ")
(display (board-who-is-winner? b6b))

(display-board b16)
(display "\nGanador de tablero b16?: ")
(display (board-who-is-winner? b16))
