(require "player_207823589_CarrascoAlvarez.rkt")
(require "board_207823589_CarrascoAlvarez.rkt")
(require "utils_207823589_CarrascoAlvarez.rkt")
(require "game_207823589_CarrascoAlvarez.rkt")

(define p1 (player 1 "YOLO" "red" 0 0 0 21))
(displayln p1)
(define p2 (player 2 "MatesMike" "yellow" 1 1 0 21))
(displayln p2)
(define p3 (player 1 "Kruskal" "maincra" 1 1 0 999))
(displayln p3)
(define p4 (player 2 "Schwartzchild" "yellow" 0 0 1 30))
(displayln p4)

;(RF11)
(define gA (game p1 p2 empty-board 1))
(define gB (game p3 p4 empty-board 1))
(define gC (game p1 p4 empty-board 2))
(display gA)
(display gB)
(display gC)

;(RF12,RF13,RF16,RF18)
(game-get-board gC)
(displayln (game-history gC))
(display "\nDraw?: ")
(display (game-is-draw? gC))
(define gC1 (game-player-set-move gC p4 0) )
(game-get-board gC1)
(define gC2 (game-player-set-move gC1 p1 1) )
(game-get-board gC2)
(define gC3 (game-player-set-move gC2 p4 0) )
(game-get-board gC3)
(displayln (game-history gC3))
(display "\nDraw?: ")
(display (game-is-draw? gC3))
(define gC4 (game-player-set-move gC3 p1 2))
(define gC5 (game-player-set-move gC4 p4 5))
(game-get-board gC5)
(displayln (game-history gc5))
(display "\nDraw?: ")
(display (game-is-draw? gC5))

;(RF14)
(displayln "\nVamos a dar un poco de wins,losses y draws a p1:")
(define p1a (player-update-stats p1 "win"))
(displayln p1a)
(define p1b (player-update-stats p1a "loss"))
(displayln p1b)
(define p1c (player-update-stats p1b "draw"))
(displayln p1c)

;(RF15)
(displayln "Jugador de la jugada antes de gC5?: ")
(displayln (game-get-current-player gC4))
(displayln "Jugador de la jugada antes de gC4?: ")
(displayln (game-get-current-player gC3))
(displayln "Jugador de la jugada antes de gC3?: ")
(displayln (game-get-current-player gC2))

;(RF17)
(displayln "End en gC1: ")
(displayln (game-set-end gC1))
(displayln "End en gC3: ")
(displayln (game-set-end gC3))
(displayln "End en gC5: ")
(displayln (game-set-end gC5))
